
"""
Quote Export Service - PDF and Excel generation for quotes
"""
import io
import os
import subprocess
import tempfile
from typing import Optional

import openpyxl
from openpyxl.styles import Font, Alignment, Border, Side
from app.models.quote import Quote


def generate_quote_pdf(quote: Quote, version: Optional[int] = None) -> bytes:
    """
    Generate a PDF for the given quote.
    Uses LibreOffice (soffice) to convert the generated Excel file to PDF.
    """
    # 1. Generate Excel first (Byte Stream)
    excel_stream = generate_quote_excel_stream(quote, version)
    
    # 2. Save to temporary file
    with tempfile.TemporaryDirectory() as tmpdirname:
        xlsx_path = os.path.join(tmpdirname, "temp_quote.xlsx")
        with open(xlsx_path, "wb") as f:
            f.write(excel_stream.getvalue())
            
        # 3. Run LibreOffice conversion
        # Command: soffice --headless --convert-to pdf --outdir <dir> <file>
        # Adjust path for macOS standard install
        soffice_path = "/Applications/LibreOffice.app/Contents/MacOS/soffice"
        if not os.path.exists(soffice_path):
             # Fallback check for linux/standard path or alias
             soffice_path = "soffice" 

        cmd = [
            soffice_path,
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            tmpdirname,
            xlsx_path
        ]
        
        try:
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            
            # 4. Read the resulting PDF
            # LibreOffice keeps the same basename: temp_quote.pdf
            pdf_path = os.path.join(tmpdirname, "temp_quote.pdf")
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    pdf_content = f.read()
                return pdf_content
            else:
                # Fallback or error?
                # If PDF generation fails, we might throw an error/log it
                raise Exception("PDF file was not generated by LibreOffice")
                
        except subprocess.CalledProcessError as e:
            print(f"LibreOffice conversion failed: {e.stderr.decode()}")
            raise Exception("Failed to convert Excel to PDF. Ensure LibreOffice is installed.")


def generate_quote_excel(quote: Quote, version: Optional[int] = None) -> bytes:
    """Wrapper to return bytes for the router."""
    stream = generate_quote_excel_stream(quote, version)
    return stream.getvalue()


def generate_quote_excel_stream(quote: Quote, version_num: Optional[int] = None) -> io.BytesIO:
    """
    Generate an Excel file for the given quote using the template.
    """
    # Load template
    # Assuming app/assets/quote_template.xlsx exists relative to project root
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    template_path = os.path.join(base_dir, "app", "assets", "quote_template.xlsx")
    
    try:
        wb = openpyxl.load_workbook(template_path)
        ws = wb.active
    except Exception as e:
        print(f"Error loading template: {e}")
        # Fallback to empty if template missing (should not happen in prod if deployed correctly)
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "報價單"

    # Remove extra sheets if any
    if len(wb.sheetnames) > 1:
        for sheet_name in wb.sheetnames:
            if sheet_name != ws.title:
                del wb[sheet_name]

    # Rename active sheet: "MMDD CustomerName"
    # Format MMDD
    ver = version_num or quote.version
    dt = quote.created_at
    mmdd = dt.strftime('%m%d')
    cust_name = quote.customer.company_name if quote.customer else "Unknown"
    
    # Sanitize sheet name (remove invalid chars: \ * ? : [ ] /)
    import re
    safe_cust_name = re.sub(r'[\\*?:/\[\]]', '_', cust_name)
    
    # Excel sheet name limit is 31 chars. e.g. "0129 ClientName v1"
    new_sheet_name = f"{mmdd} {safe_cust_name} v{ver}"
    ws.title = new_sheet_name[:31]

    # Helper to safely set cell value (handles merged cells)
    def safe_write(arg1, arg2, arg3=None):
        if isinstance(arg1, int):
            row, col, value = arg1, arg2, arg3
            cell = ws.cell(row=row, column=col)
        else:
            coord, value = arg1, arg2
            cell = ws[coord]
        
        # Check if cell is merged
        if isinstance(cell, openpyxl.cell.cell.MergedCell):
             for merged_range in ws.merged_cells.ranges:
                 if merged_range.min_row == cell.row and merged_range.min_col == cell.column:
                     # Top-left of merge
                     cell.value = value
                     return
                 elif cell.coordinate in merged_range:
                     # Find top left
                     top_left_cell = ws.cell(row=merged_range.min_row, column=merged_range.min_col)
                     top_left_cell.value = value
                     return
        else:
             cell.value = value
    
    # 1. Header Info
    # J5: Date
    safe_write('J5', quote.created_at.strftime('%Y/%m/%d'))
    
    # J6-J9: Customer Info
    if quote.customer:
        safe_write('J6', quote.customer.company_name)
        safe_write('J7', quote.customer.tax_id or "")
        safe_write('J8', quote.customer.contact_phone or "")
        safe_write('J9', quote.customer.contact_name or "")
        
    # L1: Quote No
    safe_write('L1', quote.quote_number)
    
    # I2: Title / Project Name
    safe_write('I2', quote.title)
    # J10: Template header field "項目名稱" should mirror quote title
    safe_write('J10', quote.title)

    # 2. Overwrite Table Headers (Row 16)
    # The template might have generic headers. We enforce ours.
    # E(5): Item No
    # F(6): Unit (replacing Type since QuoteItem has no type but has Unit)
    # G(7): Description (Merged G-I)
    # J(10): Qty
    # K(11): Unit Price
    # L(12): Amount
    
    safe_write(16, 5, "項次")
    safe_write(16, 6, "單位") 
    safe_write(16, 7, "項目說明")
    safe_write(16, 10, "數量")
    safe_write(16, 11, "單價")
    safe_write(16, 12, "金額")
    
    # 3. Items Logic
    start_row = 17
    current_row = start_row
    
    # Helper for row spans
    def get_row_span(row_idx):
        cell_coord = f"E{row_idx}"
        for merged_range in ws.merged_cells.ranges:
             if cell_coord in merged_range and merged_range.min_row == row_idx:
                 return merged_range.max_row - merged_range.min_row + 1
        return 1

    # Clear existing rows (17-60)
    for r in range(17, 60):
        for c in range(1, 15):
             safe_write(r, c, None)
             
    # Helper to create/check vertical merge
    def ensure_vertical_merge(col_idx, start_r, span_len):
        if span_len < 2: return
        end_r = start_r + span_len - 1
        cell = ws.cell(row=start_r, column=col_idx)
        if isinstance(cell, openpyxl.cell.cell.MergedCell):
            return
        
        is_merge_start = False
        for rng in ws.merged_cells.ranges:
            if rng.min_row == start_r and rng.min_col == col_idx and rng.max_row >= end_r:
                is_merge_start = True
                break
        
        if not is_merge_start:
            try:
                ws.merge_cells(start_row=start_r, start_column=col_idx, end_row=end_r, end_column=col_idx)
                # Apply center alignment
                top_cell = ws.cell(row=start_r, column=col_idx)
                top_cell.alignment = Alignment(horizontal='center', vertical='center')
            except Exception as e:
                print(f"Merge error at {start_r},{col_idx}: {e}")

    # Write Items
    for idx, item in enumerate(quote.items, 1):
        span = get_row_span(current_row)
        
        # Col 5 (E): Index
        safe_write(current_row, 5, str(idx))
        if span >= 2: ensure_vertical_merge(5, current_row, span)

        # Col 6 (F): Unit (Use unit_price's unit or item.unit)
        safe_write(current_row, 6, item.unit)
        if span >= 2: ensure_vertical_merge(6, current_row, span)

        # Col 7 (G): Name & Description (Merged G-I)
        # If span >= 2, we can split Name and Description into separate lines if desired.
        # Format:
        # Row 1: Name
        # Row 2: Description (Spec / Dims)
        
        if span >= 2:
            # Row 1: Name
            safe_write(current_row, 7, item.name)
            # Row 2: Description
            if item.description:
                safe_write(current_row + 1, 7, item.description)
        else:
            # Single row: Concatenate
            full_text = item.name
            if item.description:
                full_text += f"\n{item.description}"
            safe_write(current_row, 7, full_text)

        # Col 10 (J): Quantity
        safe_write(current_row, 10, float(item.quantity))
        if span >= 2: ensure_vertical_merge(10, current_row, span)

        # Col 11 (K): Unit Price
        safe_write(current_row, 11, float(item.unit_price))
        if span >= 2: ensure_vertical_merge(11, current_row, span)

        # Col 12 (L): Subtotal (Amount)
        safe_write(current_row, 12, float(item.subtotal))
        if span >= 2: ensure_vertical_merge(12, current_row, span)
        
        current_row += span

    # 4. Totals (Rows 49, 50, 51)
    # K(11): Label, L(12): Value
    
    def fmt_price(val):
        return f"NT$ {val:,.0f}"

    safe_write(49, 11, "小計:")
    safe_write(49, 12, fmt_price(quote.subtotal))
    
    safe_write(50, 11, "稅金:")
    safe_write(50, 12, fmt_price(quote.tax_total))
    
    safe_write(51, 11, "總計:")
    safe_write(51, 12, fmt_price(quote.total))
    
    # Optional: Notes in Row 53+ if template allows?
    # Template might have "備註" around row 42-46? 
    # Since I don't know the exact row for notes in template, and `export_service.py` didn't write notes, 
    # I will skip notes or try to find a safe spot.
    # `export_service.py` loops up to 60 clearing things.
    # If there is a note field, we can add it later.
    
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
