from typing import Any, Optional
import math
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app import crud, schemas
from app.database import get_db
from app.deps.auth import require_superuser
from app.models.user import User

router = APIRouter()


@router.get("", response_model=schemas.CatalogItemListResponse)
def read_catalog_items(
    db: Session = Depends(get_db),
    page: int = Query(1, ge=1, description="Page number (1-indexed)"),
    pageSize: int = Query(50, ge=1, le=150, description="Items per page (max 150)"),
    status: Optional[str] = Query(None, description="Filter by status: active | inactive"),
    type: Optional[str] = Query(None, description="Filter by type: product | service | output"),
    search: Optional[str] = Query(None, description="Search by name (fuzzy)")
) -> Any:
    """
    Get paginated catalog items.
    Always excludes soft-deleted items.
    """
    # Validate pageSize
    if pageSize not in [50, 100, 150]:
        # Allow custom values within range, but guide users
        pageSize = min(max(pageSize, 1), 150)
    
    items, total_count = crud.catalog.get_multi_with_pagination(
        db,
        page=page,
        page_size=pageSize,
        status=status,
        item_type=type,
        search=search
    )
    
    total_pages = math.ceil(total_count / pageSize) if total_count > 0 else 0
    
    return schemas.CatalogItemListResponse(
        items=items,
        meta=schemas.CatalogItemMeta(
            totalCount=total_count,
            page=page,
            pageSize=pageSize,
            totalPages=total_pages
        )
    )


@router.get("/internal", response_model=schemas.CatalogItemInternalListResponse)
def read_catalog_items_internal(
    db: Session = Depends(get_db),
    page: int = Query(1, ge=1, description="Page number (1-indexed)"),
    pageSize: int = Query(50, ge=1, le=150, description="Items per page (max 150)"),
    status: Optional[str] = Query(None, description="Filter by status: active | inactive"),
    type: Optional[str] = Query(None, description="Filter by type: product | service | output"),
    search: Optional[str] = Query(None, description="Search by name (fuzzy)"),
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Internal/admin catalog list.
    Includes internal cost fields.
    """
    if pageSize not in [50, 100, 150]:
        pageSize = min(max(pageSize, 1), 150)

    items, total_count = crud.catalog.get_multi_with_pagination(
        db,
        page=page,
        page_size=pageSize,
        status=status,
        item_type=type,
        search=search,
    )

    total_pages = math.ceil(total_count / pageSize) if total_count > 0 else 0

    return schemas.CatalogItemInternalListResponse(
        items=items,
        meta=schemas.CatalogItemMeta(
            totalCount=total_count,
            page=page,
            pageSize=pageSize,
            totalPages=total_pages,
        ),
    )


@router.get("/internal/{id}", response_model=schemas.CatalogItemInternal)
def read_catalog_item_internal(
    *,
    db: Session = Depends(get_db),
    id: str,
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Internal/admin catalog item detail.
    Includes internal cost fields.
    """
    item = crud.catalog.get(db, id=id)
    if not item:
        raise HTTPException(status_code=404, detail="Catalog Item not found")
    return item


@router.post("", response_model=schemas.CatalogItemInternal, status_code=201)
def create_catalog_item(
    *,
    db: Session = Depends(get_db),
    item_in: schemas.CatalogItemCreate,
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Create a new catalog item.
    - item_no is auto-generated by backend
    - Validates name uniqueness (returns 409 if duplicate)
    - Applies type-based default unit if not provided
    """
    try:
        item = crud.catalog.create_with_item_no(db, obj_in=item_in)
        
        # Audit log
        crud.audit_log.log_action(
            db,
            entity_type="catalog_item",
            entity_id=item.id,
            action="create"
        )
        
        return item
    except ValueError as e:
        # Name uniqueness violation
        raise HTTPException(status_code=409, detail=str(e))


@router.post("/resolve", response_model=list[schemas.CatalogItemResolveItem])
def resolve_catalog_items(
    *,
    db: Session = Depends(get_db),
    request: schemas.CatalogItemResolveRequest,
) -> Any:
    """
    Batch resolve lightweight catalog metadata for quote/rfq editing flows.
    Returns only the fields needed by the frontend to avoid N detail calls.
    """
    unique_ids = list(dict.fromkeys(request.ids))
    if not unique_ids:
        return []

    items = crud.catalog.get_multi_by_ids(db, ids=unique_ids)
    item_map = {item.id: item for item in items}

    return [
        schemas.CatalogItemResolveItem.model_validate(item_map[item_id])
        for item_id in unique_ids
        if item_id in item_map
    ]


@router.get("/{id}", response_model=schemas.CatalogItemPublic)
def read_catalog_item(
    *,
    db: Session = Depends(get_db),
    id: str
) -> Any:
    """
    Get catalog item by ID.
    Returns 404 if item is soft-deleted.
    """
    item = crud.catalog.get(db, id=id)
    if not item:
        raise HTTPException(status_code=404, detail="Catalog Item not found")
    return item


@router.put("/{id}", response_model=schemas.CatalogItemInternal)
def update_catalog_item(
    *,
    db: Session = Depends(get_db),
    id: str,
    item_in: schemas.CatalogItemUpdate,
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Update catalog item.
    Validates name uniqueness (excluding self).
    """
    item = crud.catalog.get(db, id=id)
    if not item:
        raise HTTPException(status_code=404, detail="Catalog Item not found")
    
    try:
        updated_item = crud.catalog.update_with_validation(db, db_obj=item, obj_in=item_in)
        
        # Audit log
        crud.audit_log.log_action(
            db,
            entity_type="catalog_item",
            entity_id=updated_item.id,
            action="update"
        )
        
        return updated_item
    except ValueError as e:
        # Name uniqueness violation
        raise HTTPException(status_code=409, detail=str(e))


@router.post("/{id}/inactivate", response_model=schemas.CatalogItemInternal)
def inactivate_catalog_item(
    *,
    db: Session = Depends(get_db),
    id: str,
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Set catalog item status to inactive.
    Item remains in database and can be queried with status=inactive filter.
    """
    item = crud.catalog.get(db, id=id)
    if not item:
        raise HTTPException(status_code=404, detail="Catalog Item not found")
    
    item = crud.catalog.inactivate(db, id=id)
    
    # Audit log
    crud.audit_log.log_action(
        db,
        entity_type="catalog_item",
        entity_id=item.id,
        action="inactivate"
    )
    
    return item


@router.post("/{id}/reactivate", response_model=schemas.CatalogItemInternal)
def reactivate_catalog_item(
    *,
    db: Session = Depends(get_db),
    id: str,
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Reactivate an inactive catalog item.
    Sets status back to active.
    """
    try:
        item = crud.catalog.reactivate(db, id=id)
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
        
    if not item:
        raise HTTPException(status_code=404, detail="Catalog Item not found")
    
    # Audit log (audit log needs item id, which we have from result)
    crud.audit_log.log_action(
        db,
        entity_type="catalog_item",
        entity_id=item.id,
        action="reactivate"
    )
    
    return item

@router.delete("/{id}", response_model=schemas.CatalogItemInternal)
def delete_catalog_item(
    *,
    db: Session = Depends(get_db),
    id: str,
    current_user: User = Depends(require_superuser),
) -> Any:
    """
    Soft delete catalog item.
    Item will no longer appear in list/get queries.
    Data is retained in database for audit purposes.
    """
    item = crud.catalog.get(db, id=id)
    if not item:
        raise HTTPException(status_code=404, detail="Catalog Item not found")
    
    deleted_item = crud.catalog.soft_delete(db, id=id)
    
    # Audit log
    crud.audit_log.log_action(
        db,
        entity_type="catalog_item",
        entity_id=deleted_item.id,
        action="delete"
    )
    
    return deleted_item
