from datetime import datetime
from decimal import Decimal
from typing import Optional, List, Literal
from pydantic import BaseModel, ConfigDict, Field


# ===== Base Schemas =====

class CatalogItemBase(BaseModel):
    """Public schema - excludes internal cost data"""
    name: str
    type: Literal["product", "service", "output"]
    unit: str
    default_price: Decimal
    status: str = "active"
    description: Optional[str] = None
    notes: Optional[str] = None
    category: Optional[str] = None
    tax_category: Optional[str] = None


class CatalogItemCreate(BaseModel):
    """Create schema - includes reference_cost, but item_no is generated by backend"""
    name: str
    type: Literal["product", "service", "output"]
    unit: Optional[str] = None  # Optional: backend will use default based on type
    reference_cost: Decimal
    default_price: Decimal
    status: str = "active"
    description: Optional[str] = None
    notes: Optional[str] = None
    category: Optional[str] = None
    tax_category: Optional[str] = None


class CatalogItemUpdate(BaseModel):
    """Update schema - all fields optional"""
    name: Optional[str] = None
    type: Optional[Literal["product", "service", "output"]] = None
    unit: Optional[str] = None
    reference_cost: Optional[Decimal] = None
    default_price: Optional[Decimal] = None
    status: Optional[str] = None
    description: Optional[str] = None
    notes: Optional[str] = None
    category: Optional[str] = None
    tax_category: Optional[str] = None


# ===== Response Schemas =====

class CatalogItemPublic(CatalogItemBase):
    """Public response schema - excludes reference_cost"""
    id: str
    item_no: str
    type: Literal["product", "service", "output"]
    created_at: datetime
    updated_at: datetime
    
    model_config = ConfigDict(from_attributes=True)


class CatalogItemInternal(CatalogItemPublic):
    """Internal schema - includes reference_cost and deleted_at"""
    reference_cost: Decimal
    deleted_at: Optional[datetime] = None


# ===== Pagination Schemas =====

class CatalogItemMeta(BaseModel):
    """Pagination metadata"""
    totalCount: int = Field(..., description="Total number of items matching the query")
    page: int = Field(..., description="Current page number (1-indexed)")
    pageSize: int = Field(..., description="Number of items per page")
    totalPages: int = Field(..., description="Total number of pages")


class CatalogItemListResponse(BaseModel):
    """Paginated list response"""
    items: List[CatalogItemPublic]
    meta: CatalogItemMeta


class CatalogItemInternalListResponse(BaseModel):
    """Paginated list response (internal/admin)"""
    items: List[CatalogItemInternal]
    meta: CatalogItemMeta


class CatalogItemResolveRequest(BaseModel):
    ids: List[str]


class CatalogItemResolveItem(BaseModel):
    id: str
    name: str
    type: Literal["product", "service", "output"]
    unit: str
    category: Optional[str] = None

# Backward-compatible alias
CatalogItem = CatalogItemPublic
