"""add_rfq_deleted_at_for_soft_delete

Revision ID: 0d11176827a9
Revises: f140e669adf2
Create Date: 2026-01-19 15:47:43.348822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d11176827a9'
down_revision: Union[str, None] = 'f140e669adf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'deleted_at')
    # ### end Alembic commands ###
