"""make_quote_rfq_id_nullable

Revision ID: 144f4b2c2d12
Revises: e8478e46bbab
Create Date: 2026-01-25 00:43:39.676318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144f4b2c2d12'
down_revision: Union[str, None] = 'e8478e46bbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'rfq_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'rfq_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
