"""Fix customer schema mismatch

Revision ID: 27c8ca4dcd57
Revises: 005_remove_unique_name
Create Date: 2026-01-13 22:49:08.377048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '27c8ca4dcd57'
down_revision: Union[str, None] = '005_remove_unique_name'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use inspector to check if column exists
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    columns = [c['name'] for c in inspector.get_columns('customers')]
    
    op.drop_index(op.f('ix_catalog_items_name'), table_name='catalog_items')
    
    if 'company_email' not in columns:
        op.add_column('customers', sa.Column('company_email', sa.String(), nullable=True))
        
    op.alter_column('customers', 'tax_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'tax_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('customers', 'company_email')
    op.create_index(op.f('ix_catalog_items_name'), 'catalog_items', ['name'], unique=False)
    # ### end Alembic commands ###
