"""add_rfq_versions_table

Revision ID: 526bd44673ca
Revises: 27c8ca4dcd57
Create Date: 2026-01-16 16:23:27.504885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '526bd44673ca'
down_revision: Union[str, None] = '27c8ca4dcd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfq_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfq_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('vendor_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('required_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tax_setting', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rfq_items', sa.Column('rfq_version_id', sa.String(), nullable=False))
    op.add_column('rfq_items', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('rfq_items', sa.Column('item_type', sa.String(length=20), nullable=False))
    op.add_column('rfq_items', sa.Column('spec_notes', sa.Text(), nullable=True))
    op.add_column('rfq_items', sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('rfq_items', sa.Column('line_subtotal', sa.Numeric(precision=15, scale=2), nullable=False))
    op.alter_column('rfq_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('rfq_items_rfq_id_fkey'), 'rfq_items', type_='foreignkey')
    op.create_foreign_key(None, 'rfq_items', 'rfq_versions', ['rfq_version_id'], ['id'])
    op.drop_column('rfq_items', 'reference_cost')
    op.drop_column('rfq_items', 'notes')
    op.drop_column('rfq_items', 'selling_price')
    op.drop_column('rfq_items', 'type')
    op.drop_column('rfq_items', 'rfq_id')
    op.drop_column('rfq_items', 'tax_category')
    op.add_column('rfqs', sa.Column('rfq_no', sa.String(length=20), nullable=False))
    op.add_column('rfqs', sa.Column('project_name', sa.String(length=255), nullable=False))
    op.add_column('rfqs', sa.Column('vendor_id', sa.String(), nullable=False))
    op.add_column('rfqs', sa.Column('current_version_id', sa.String(), nullable=True))
    op.add_column('rfqs', sa.Column('selected_version_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_rfqs_rfq_no'), 'rfqs', ['rfq_no'], unique=True)
    op.drop_constraint(op.f('rfqs_customer_id_fkey'), 'rfqs', type_='foreignkey')
    op.create_foreign_key(None, 'rfqs', 'vendors', ['vendor_id'], ['id'])
    op.drop_column('rfqs', 'title')
    op.drop_column('rfqs', 'description')
    op.drop_column('rfqs', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rfqs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rfqs', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.create_foreign_key(op.f('rfqs_customer_id_fkey'), 'rfqs', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_rfqs_rfq_no'), table_name='rfqs')
    op.drop_column('rfqs', 'selected_version_id')
    op.drop_column('rfqs', 'current_version_id')
    op.drop_column('rfqs', 'vendor_id')
    op.drop_column('rfqs', 'project_name')
    op.drop_column('rfqs', 'rfq_no')
    op.add_column('rfq_items', sa.Column('tax_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rfq_items', sa.Column('rfq_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rfq_items', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rfq_items', sa.Column('selling_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rfq_items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rfq_items', sa.Column('reference_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rfq_items', type_='foreignkey')
    op.create_foreign_key(op.f('rfq_items_rfq_id_fkey'), 'rfq_items', 'rfqs', ['rfq_id'], ['id'])
    op.alter_column('rfq_items', 'quantity',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('rfq_items', 'line_subtotal')
    op.drop_column('rfq_items', 'unit_price')
    op.drop_column('rfq_items', 'spec_notes')
    op.drop_column('rfq_items', 'item_type')
    op.drop_column('rfq_items', 'sort_order')
    op.drop_column('rfq_items', 'rfq_version_id')
    op.drop_table('rfq_versions')
    # ### end Alembic commands ###
