"""add_quote_tax_setting

Revision ID: 83f71589f21f
Revises: d19d13cdd3e0
Create Date: 2026-01-28 23:22:12.367186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f71589f21f'
down_revision: Union[str, None] = 'd19d13cdd3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('accounting_status', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.add_column('quotes', sa.Column('tax_setting', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'tax_setting')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'deleted_at')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'accounting_status')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
