"""unify_customer_vendor_rfq_final

Revision ID: 96c4ff4f672d
Revises: fdb9cc7dfbb5
Create Date: 2026-01-20 15:49:17.044367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c4ff4f672d'
down_revision: Union[str, None] = 'fdb9cc7dfbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('customers', sa.Column('default_currency', sa.String(), nullable=True)) # REVERTED: Exists
    # op.add_column('customers', sa.Column('default_payment_terms', sa.String(), nullable=True)) # REVERTED: Exists
    op.drop_constraint(op.f('rfqs_vendor_id_fkey'), 'rfqs', type_='foreignkey')
    
    # Data Cleanup: Remove RFQs with invalid vendors (vendors that are not in customers table)
    op.execute("DELETE FROM rfq_items WHERE rfq_version_id IN (SELECT id FROM rfq_versions WHERE rfq_id IN (SELECT id FROM rfqs WHERE vendor_id NOT IN (SELECT id FROM customers)))")
    op.execute("DELETE FROM rfq_versions WHERE rfq_id IN (SELECT id FROM rfqs WHERE vendor_id NOT IN (SELECT id FROM customers))")
    op.execute("DELETE FROM rfqs WHERE vendor_id NOT IN (SELECT id FROM customers)")
    
    op.create_foreign_key(None, 'rfqs', 'customers', ['vendor_id'], ['id'])
    # op.drop_column('rfqs', 'deleted_at') # REVERTED: We need deleted_at for soft delete
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('rfqs', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)) # REVERTED
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.create_foreign_key(op.f('rfqs_vendor_id_fkey'), 'rfqs', 'vendors', ['vendor_id'], ['id'])
    # op.drop_column('customers', 'default_payment_terms')
    # op.drop_column('customers', 'default_currency')
    # ### end Alembic commands ###
