"""Add UserStatus UserRole and RegistrationRequest

Revision ID: c0366a019b5e
Revises: 718d98fe04b3
Create Date: 2026-02-16 21:28:26.567791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0366a019b5e'
down_revision: Union[str, None] = '718d98fe04b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums manually for Postgres
    # RegistrationStatus is created by create_table automatically? Let's check.
    # If create_table fails with duplicate type, it implies it does.
    # So we only create UserStatus and UserRole which are used in add_column.
    sa.Enum('PENDING_PASSWORD', 'ACTIVE', 'DISABLED', name='userstatus').create(op.get_bind())
    sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole').create(op.get_bind())

    op.create_table('registration_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registrationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=True)
    op.create_index(op.f('ix_registration_requests_id'), 'registration_requests', ['id'], unique=False)
    
    # Add columns with server_default to handle existing rows
    op.add_column('users', sa.Column('status', sa.Enum('PENDING_PASSWORD', 'ACTIVE', 'DISABLED', name='userstatus'), server_default='ACTIVE', nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole'), server_default='OWNER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'status')
    op.drop_index(op.f('ix_registration_requests_id'), table_name='registration_requests')
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.drop_table('registration_requests')
    
    # Drop Enums manually
    sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole').drop(op.get_bind())
    sa.Enum('PENDING_PASSWORD', 'ACTIVE', 'DISABLED', name='userstatus').drop(op.get_bind())
    # sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registrationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
