"""add_quote_status_accounting_version

Revision ID: d19d13cdd3e0
Revises: 144f4b2c2d12
Create Date: 2026-01-25 14:00:32.414102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19d13cdd3e0'
down_revision: Union[str, None] = '144f4b2c2d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('accounting_status', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'version')
    op.drop_column('quotes', 'accounting_status')
    # ### end Alembic commands ###
