"""add activated status

Revision ID: df29ac5e0b99
Revises: c0366a019b5e
Create Date: 2026-02-17 21:08:52.970381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df29ac5e0b99'
down_revision: Union[str, None] = 'c0366a019b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE registrationstatus ADD VALUE 'ACTIVATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
