"""add_quote_number

Revision ID: e8478e46bbab
Revises: 20260122_currency
Create Date: 2026-01-25 00:19:55.937712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8478e46bbab'
down_revision: Union[str, None] = '20260122_currency'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('quote_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'quotes', ['quote_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='unique')
    op.drop_column('quotes', 'quote_number')
    # ### end Alembic commands ###
