"""add_accounting_status_to_rfq

Revision ID: f140e669adf2
Revises: 526bd44673ca
Create Date: 2026-01-17 14:20:08.045805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f140e669adf2'
down_revision: Union[str, None] = '526bd44673ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column with server_default to handle existing rows
    op.add_column('rfqs', sa.Column('accounting_status', sa.String(length=20), nullable=False, server_default='unfulfilled'))
    # Remove server_default after column is added (optional, keeps schema clean)
    op.alter_column('rfqs', 'accounting_status', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'accounting_status')
    # ### end Alembic commands ###
