"""add roles column to customers

Revision ID: fdb9cc7dfbb5
Revises: 0d11176827a9
Create Date: 2026-01-20 15:06:44.997781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb9cc7dfbb5'
down_revision: Union[str, None] = '0d11176827a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('roles', sa.JSON(), nullable=False, server_default='["customer"]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'roles')
    # ### end Alembic commands ###
